auth:
    digital-ocean:
        client-id:  ...
        api-key:    ...
        location:   New York 2
    aws:
        id:     ...
        key:    ...

ssh:
    id_rsa: |
        -----BEGIN RSA PRIVATE KEY-----
        ... key here ...
        -----END RSA PRIVATE KEY-----
    id_rsa_pub: ... pub key here ...